version: '3.8'
services:
  web:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal web-server --bind 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
    env_file: .env

  worker:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal worker
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env

  smtp:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal smtp-server
    ports:
      - "25:25"
    volumes:
      - ./config:/config
    env_file: .env
