version: 2

general:
  use_ip_pools: false

web:
  host: supportdeckhub.com
  protocol: http

web_server:
  bind_address: 0.0.0.0
  port: 5000

smtp_server:
  port: 25

logging:
  stdout: true

main_db:
  host: 172.17.0.1
  port: 3306
  username: postal
  password: "Apple@012345"
  database: postal

message_db:
  host: 172.17.0.1
  port: 3306
  username: postal
  password: "Apple@012345"
  prefix: postal

rabbitmq:
  host: 172.17.0.1
  port: 5672
  username: postal
  password: "Apple@012345"
  vhost: /postal

dns:
  mx_records:
    - mx.supportdeckhub.com
  spf_include: spf.supportdeckhub.com
  return_path_domain: rp.supportdeckhub.com
  route_domain: routes.supportdeckhub.com
  track_domain: track.supportdeckhub.com

smtp:
  host: 127.0.0.1
  port: 2525
  from_name: Postal
  from_address: postal@supportdeckhub.com

rails:
  secret_key: 8b61319579d52f87d925f41fc7471c31ac8cb6b48156647555c5f3bf7089448fe0510c152f15de05aac9306
