version: 2

general:
  use_ip_pools: false

web:
  host: supportdeckhub.com
  protocol: http

web_server:
  bind_address: 0.0.0.0
  port: 5000

smtp_server:
  port: 25

logging:
  stdout: true

main_db:
  host: <%= ENV.fetch('POSTAL_DB_HOST', '172.17.0.1') %>
  port: <%= ENV.fetch('POSTAL_DB_PORT', 3306) %>
  username: <%= ENV.fetch('POSTAL_DB_USER', 'postal') %>
  password: <%= ENV.fetch('POSTAL_DB_PASS', 'Apple@012345') %>
  database: <%= ENV.fetch('POSTAL_DB_NAME', 'postal') %>

message_db:
  host: <%= ENV.fetch('POSTAL_MESSAGE_DB_HOST', ENV.fetch('POSTAL_DB_HOST', '172.17.0.1')) %>
  port: <%= ENV.fetch('POSTAL_MESSAGE_DB_PORT', ENV.fetch('POSTAL_DB_PORT', 3306)) %>
  username: <%= ENV.fetch('POSTAL_MESSAGE_DB_USER', ENV.fetch('POSTAL_DB_USER', 'postal')) %>
  password: <%= ENV.fetch('POSTAL_MESSAGE_DB_PASS', ENV.fetch('POSTAL_DB_PASS', 'Apple@012345')) %>
  prefix: <%= ENV.fetch('POSTAL_MESSAGE_DB_PREFIX', 'postal') %>

rabbitmq:
  host: <%= ENV.fetch('POSTAL_RABBITMQ_HOST', '172.17.0.1') %>
  port: <%= ENV.fetch('POSTAL_RABBITMQ_PORT', 5672) %>
  username: <%= ENV.fetch('POSTAL_RABBITMQ_USER', 'postal') %>
  password: <%= ENV.fetch('POSTAL_RABBITMQ_PASS', 'Apple@012345') %>
  vhost: <%= ENV.fetch('POSTAL_RABBITMQ_VHOST', '/postal') %>

dns:
  mx_records:
    - mx.supportdeckhub.com
  spf_include: spf.supportdeckhub.com
  return_path_domain: rp.supportdeckhub.com
  route_domain: routes.supportdeckhub.com
  track_domain: track.supportdeckhub.com

smtp:
  host: 127.0.0.1
  port: 2525
  from_name: Postal
  from_address: postal@supportdeckhub.com

rails:
  secret_key: <%= ENV.fetch('POSTAL_SECRET_KEY', 'change_me') %>
